export const ORDER_ABI = [
  "function submitToLenderTransferProof(bytes rawData, uint32 blockHeight, (bytes32[] proof, bytes32 root, bytes32 leaf, bool[] flags) merkleProof, uint32 toLenderTxIndex) external",
  "function submitRenewalOrderProof(bytes rawData, uint32 blockHeight, (bytes32[] proof, bytes32 root, bytes32 leaf, bool[] flags) merkleProof) external",
  "function confirmRepaymentFromBalance(string borrowerBtcAddress) external",
  "function setTimeoutRepayEnabled(bool enabled) external",
  "function executeIncreaseRequest() external",
];

export const ISSUER_ABI = [
  "function submitRegularUnlockTransferProof(address order, bytes txData, uint32 blockHeight, (bytes32[] proof, bytes32 root, bytes32 leaf, bool[] flags) merkleProof) external",
  "function cancelObsidianIncrease(address order) external",
];

// Custom error definitions across the contracts the proof flow can touch (ObsidianOrder,
// Issuer, LoanContract, LoanTools, TaprootTools, ObsidianBtcAddressBinder, Order). Needed
// so a revert is shown as its error NAME instead of a raw 4-byte selector hash.
// Regenerate from the contract ABIs after upgrades.
export const ERROR_ABI = [
  "error AddressEmptyCode(address target)",
  "error AddressInsufficientBalance(address account)",
  "error AlreadyCreated()",
  "error EmptyBtcAddress()",
  "error ErrorStatus()",
  "error ExceedsMaxBorrow()",
  "error FailedInnerCall()",
  "error IncreaseWindowClosed()",
  "error InsufficientRepaymentBalance()",
  "error InvalidDeadline()",
  "error InvalidInitialization()",
  "error InvalidParameters()",
  "error InvalidUnlockAmount()",
  "error InvalidVersion()",
  "error LenderOnly()",
  "error MathOverflowedMulDiv()",
  "error NoOpen()",
  "error NoPermission()",
  "error NotCloseable()",
  "error NotInitializing()",
  "error NotRenewalOperator()",
  "error OnlyBorrower()",
  "error OrderClosedAlready()",
  "error OrderTimedOut()",
  "error OwnableInvalidOwner(address owner)",
  "error OwnableUnauthorizedAccount(address account)",
  "error ReentrancyGuardReentrantCall()",
  "error RenewalWindowNotOpen()",
  "error SafeERC20FailedOperation(address token)",
  "error TimelockOverflow()",
  "error TimeoutRepayDisabled()",
  "error ArbitratorNotActive()",
  "error ArrayMismatch()",
  "error DelayOneBlock()",
  "error EmptyAddress()",
  "error InsufficientCollateral()",
  "error InvalidAmount()",
  "error InvalidMerkleRoot()",
  "error InvalidStatus()",
  "error InvalidTaprootKey()",
  "error InvalidTxId()",
  "error InvalidUtxo()",
  "error LoanTooLarge()",
  "error LoanTooSmall()",
  "error NoBtcUtils()",
  "error NoRenewalManager()",
  "error NoTapRootUnlock()",
  "error NoToken()",
  "error NoUnlockTx()",
  "error NotAuthorizedApp()",
  "error OnlyOrdersAllowed()",
  "error VerifyFailed()",
  "error BindingInUse(uint256 tokenId, address activeOrder)",
  "error BtcAddressAlreadyBound(bytes32 btcAddressHash)",
  "error BtcAddressAlreadyUsed(bytes32 btcAddressHash)",
  "error BtcAddressMismatch(uint256 tokenId, bytes32 expectedHash, bytes32 actualHash)",
  "error CollateralTxIdAlreadyUsed(bytes32 txId)",
  "error InvalidCollateralTxId()",
  "error NotActiveOrder(address caller, uint256 tokenId)",
  "error NotBinderOwner(address caller)",
  "error NotConsumerManager(address account)",
  "error NotTokenOwner(address user, uint256 tokenId)",
  "error NotValidOrder(address order)",
  "error TokenAlreadyBound(uint256 tokenId)",
  "error TokenNotBound(uint256 tokenId)",
  "error ZeroAddress()",
  "error AllowanceTooLow()",
  "error ArbitrationUnavailable()",
  "error ArbitratorDeadlineNotPassed()",
  "error ArbitratorOnly()",
  "error InvalidBtcData()",
  "error InvalidLender()",
  "error InvalidPreimage()",
  "error InvalidProofLeaf()",
  "error InvalidRepaidExpireWindow()",
  "error InvalidScriptTimelock()",
  "error InvalidSignature()",
  "error InvalidTaprootLeaves()",
  "error InvalidTimelock()",
  "error InvalidV2TaprootLeaves()",
  "error NoSubmitPledgeProof()",
  "error NotReady()",
  "error OnlyV2()",
];

// Let the contract instances decode their own custom errors (ethers v6 then populates
// error.revert on a revert), and build a standalone interface for explicit decoding.
ORDER_ABI.push(...ERROR_ABI);
ISSUER_ABI.push(...ERROR_ABI);
export const ERROR_INTERFACE = new ethers.Interface(ERROR_ABI);
