import { LANG_STORAGE_KEY } from "./i18n.js";

export const state = {
  provider: null,
  signer: null,
  account: null,
  chainIdHex: null,
  walletProvider: null,
  walletLabel: "",
  discoveredWallets: [],
  locale: (() => {
    try {
      return localStorage.getItem(LANG_STORAGE_KEY) || "zh";
    } catch {
      return "zh";
    }
  })(),
};

export const elements = {
  brandTitle: document.getElementById("brand-title"),
  brandSubtitle: document.getElementById("brand-subtitle"),
  topbarNote: document.getElementById("topbar-note"),
  languageToggleButton: document.getElementById("language-toggle-button"),
  form: document.getElementById("submit-form"),
  submitHeading: document.getElementById("submit-heading"),
  submitTag: document.getElementById("submit-tag"),
  submitEyebrow: document.getElementById("submit-eyebrow"),
  sidebarLabel: document.getElementById("sidebar-label"),
  configTitle: document.getElementById("config-title"),
  networkLabel: document.getElementById("network-label"),
  network: document.getElementById("network"),
  proofTypeLabel: document.getElementById("proof-type-label"),
  proofType: document.getElementById("proof-type"),
  proofTypePledge: document.getElementById("proof-type-pledge"),
  proofTypeUnlock: document.getElementById("proof-type-unlock"),
  proofTypeRenewal: document.getElementById("proof-type-renewal"),
  proofTypeRenewalTopup: document.getElementById("proof-type-renewal-topup"),
  proofTypeRepayment: document.getElementById("proof-type-repayment"),
  proofTypeTimeoutRepay: document.getElementById("proof-type-timeout-repay"),
  proofTypeExecuteIncrease: document.getElementById("proof-type-execute-increase"),
  proofTypeCancelIncrease: document.getElementById("proof-type-cancel-increase"),
  paramsTitle: document.getElementById("params-title"),
  orderAddressLabel: document.getElementById("order-address-label"),
  orderAddress: document.getElementById("order-address"),
  timeoutRepayRow: document.getElementById("timeout-repay-row"),
  timeoutRepayEnabledLabel: document.getElementById("timeout-repay-enabled-label"),
  timeoutRepayEnabled: document.getElementById("timeout-repay-enabled"),
  timeoutRepayEnabledOn: document.getElementById("timeout-repay-enabled-on"),
  timeoutRepayEnabledOff: document.getElementById("timeout-repay-enabled-off"),
  borrowerBtcRow: document.getElementById("borrower-btc-row"),
  borrowerBtcLabel: document.getElementById("borrower-btc-label"),
  borrowerBtcAddress: document.getElementById("borrower-btc-address"),
  btcTxidRow: document.getElementById("btc-txid-row"),
  btcTxidLabel: document.getElementById("btc-txid-label"),
  btcTxid: document.getElementById("btc-txid"),
  formFooterNote: document.getElementById("form-footer-note"),
  networkCardTitle: document.getElementById("network-card-title"),
  issuerTitle: document.getElementById("issuer-title"),
  explorerTitle: document.getElementById("explorer-title"),
  walletCardTitle: document.getElementById("wallet-card-title"),
  actionCardTitle: document.getElementById("action-card-title"),
  resultCardTitle: document.getElementById("result-card-title"),
  walletConnectButton: document.getElementById("wallet-connect-button"),
  walletModal: document.getElementById("wallet-modal"),
  walletModalTitle: document.getElementById("wallet-modal-title"),
  walletModalClose: document.getElementById("wallet-modal-close"),
  walletList: document.getElementById("wallet-list"),
  submitProof: document.getElementById("submit-proof"),
  walletStatus: document.getElementById("wallet-status"),
  actionStatus: document.getElementById("action-status"),
  resultBox: document.getElementById("result-box"),
  networkRpc: document.getElementById("network-rpc"),
  networkChainId: document.getElementById("network-chain-id"),
  networkIssuer: document.getElementById("network-issuer"),
  networkExplorer: document.getElementById("network-explorer"),
};
